// File generated by the BNF Converter (bnfc 2.9.3).

package cmm.Absyn;

public class SBlock  extends Stm {
  public final ListStm liststm_;
  public SBlock(ListStm p1) { liststm_ = p1; }

  public <R,A> R accept(cmm.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cmm.Absyn.SBlock) {
      cmm.Absyn.SBlock x = (cmm.Absyn.SBlock)o;
      return this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststm_.hashCode();
  }


}
