// File generated by the BNF Converter (bnfc 2.9.3).

package arithm;

/** Abstract Visitor */

public class AbstractVisitor<R,A> implements AllVisitor<R,A> {
    /* Exp */
    public R visit(arithm.Absyn.EAdd p, A arg) { return visitDefault(p, arg); }
    public R visit(arithm.Absyn.EMul p, A arg) { return visitDefault(p, arg); }
    public R visit(arithm.Absyn.EInt p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(arithm.Absyn.Exp p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }

}
