// File generated by the BNF Converter (bnfc 2.9.3).

package arithm;
/** Composition Visitor
*/

public class ComposVisitor<A> implements
  arithm.Absyn.Exp.Visitor<arithm.Absyn.Exp,A>
{
    /* Exp */
    public arithm.Absyn.Exp visit(arithm.Absyn.EAdd p, A arg)
    {
      arithm.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      arithm.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new arithm.Absyn.EAdd(exp_1, exp_2);
    }
    public arithm.Absyn.Exp visit(arithm.Absyn.EMul p, A arg)
    {
      arithm.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      arithm.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new arithm.Absyn.EMul(exp_1, exp_2);
    }
    public arithm.Absyn.Exp visit(arithm.Absyn.EInt p, A arg)
    {
      Integer integer_ = p.integer_;
      return new arithm.Absyn.EInt(integer_);
    }
}
