// File generated by the BNF Converter (bnfc 2.9.3).

package cmm.Absyn;

public abstract class BoolLit implements java.io.Serializable {
  public abstract <R,A> R accept(BoolLit.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(cmm.Absyn.LTrue p, A arg);
    public R visit(cmm.Absyn.LFalse p, A arg);

  }

}
