// File generated by the BNF Converter (bnfc 2.9.3).

package arithm.Absyn;

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(arithm.Absyn.EAdd p, A arg);
    public R visit(arithm.Absyn.EMul p, A arg);
    public R visit(arithm.Absyn.EInt p, A arg);

  }

}
