// File generated by the BNF Converter (bnfc 2.9.3).

package fun;

/** All Visitor */

public interface AllVisitor<R,A> extends
  fun.Absyn.Program.Visitor<R,A>,
  fun.Absyn.Main.Visitor<R,A>,
  fun.Absyn.Def.Visitor<R,A>,
  fun.Absyn.Exp.Visitor<R,A>
{}
