// File generated by the BNF Converter (bnfc 2.9.3).

package calc;

public class PrettyPrinter
{
  //For certain applications increasing the initial size of the buffer may improve performance.
  private static final int INITIAL_BUFFER_SIZE = 128;
  private static final int INDENT_WIDTH = 2;
  //You may wish to change the parentheses used in precedence.
  private static final String _L_PAREN = new String("(");
  private static final String _R_PAREN = new String(")");
  //You may wish to change render
  private static void render(String s)
  {
    if (s.equals("{"))
    {
       onEmptyLine();
       buf_.append(s);
       _n_ = _n_ + INDENT_WIDTH;
       buf_.append("\n");
       indent();
    }
    else if (s.equals("(") || s.equals("["))
       buf_.append(s);
    else if (s.equals(")") || s.equals("]"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals("}"))
    {
       _n_ = _n_ - INDENT_WIDTH;
       onEmptyLine();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals(","))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals(";"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals("")) return;
    else if (s.trim().equals(""))
    {
       backup();
       buf_.append(s);
    }
    else
    {
       buf_.append(s);
       buf_.append(" ");
    }
  }


  //  print and show methods are defined for each category.
  public static String print(calc.Absyn.Program foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(calc.Absyn.Program foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(calc.Absyn.Def foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(calc.Absyn.Def foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(calc.Absyn.ListDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(calc.Absyn.ListDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(calc.Absyn.ListArg foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(calc.Absyn.ListArg foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(calc.Absyn.Arg foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(calc.Absyn.Arg foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(calc.Absyn.Stm foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(calc.Absyn.Stm foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(calc.Absyn.ListStm foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(calc.Absyn.ListStm foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(calc.Absyn.Exp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(calc.Absyn.Exp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(calc.Absyn.ListExp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(calc.Absyn.ListExp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(calc.Absyn.ListId foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(calc.Absyn.ListId foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(calc.Absyn.Type foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(calc.Absyn.Type foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  /***   You shouldn't need to change anything beyond this point.   ***/

  private static void pp(calc.Absyn.Program foo, int _i_)
  {
    if (foo instanceof calc.Absyn.ProgDef)
    {
       calc.Absyn.ProgDef _progdef = (calc.Absyn.ProgDef) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_progdef.listdef_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(calc.Absyn.Def foo, int _i_)
  {
    if (foo instanceof calc.Absyn.QualConstDef)
    {
       calc.Absyn.QualConstDef _qualconstdef = (calc.Absyn.QualConstDef) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("using");
       pp(_qualconstdef.exp_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.FuncDef)
    {
       calc.Absyn.FuncDef _funcdef = (calc.Absyn.FuncDef) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_funcdef.type_, 0);
       pp(_funcdef.id_, 0);
       render("(");
       pp(_funcdef.listarg_, 0);
       render(")");
       render("{");
       pp(_funcdef.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(calc.Absyn.ListDef foo, int _i_)
  {
    ppListDef(foo.iterator(), _i_);
  }

  private static void ppListDef(java.util.Iterator<calc.Absyn.Def> it, int _i_)
  {
    if (it.hasNext())
    { /* cons */
      calc.Absyn.Def el = it.next();
      pp(el, _i_); ppListDef(it, _i_);
    }
  }


  private static void pp(calc.Absyn.ListArg foo, int _i_)
  {
    ppListArg(foo.iterator(), _i_);
  }

  private static void ppListArg(java.util.Iterator<calc.Absyn.Arg> it, int _i_)
  {
    if (it.hasNext())
    {
      calc.Absyn.Arg el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListArg(it, _i_);
      }
    }
  }


  private static void pp(calc.Absyn.Arg foo, int _i_)
  {
    if (foo instanceof calc.Absyn.ArgDecl)
    {
       calc.Absyn.ArgDecl _argdecl = (calc.Absyn.ArgDecl) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_argdecl.type_, 0);
       pp(_argdecl.id_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(calc.Absyn.Stm foo, int _i_)
  {
    if (foo instanceof calc.Absyn.StmDef)
    {
       calc.Absyn.StmDef _stmdef = (calc.Absyn.StmDef) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_stmdef.exp_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.StmDecl)
    {
       calc.Absyn.StmDecl _stmdecl = (calc.Absyn.StmDecl) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_stmdecl.type_, 0);
       pp(_stmdecl.id_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.StmDecl2)
    {
       calc.Absyn.StmDecl2 _stmdecl2 = (calc.Absyn.StmDecl2) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_stmdecl2.exp_, 0);
       pp(_stmdecl2.id_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.StmDecls)
    {
       calc.Absyn.StmDecls _stmdecls = (calc.Absyn.StmDecls) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_stmdecls.type_, 0);
       pp(_stmdecls.id_, 0);
       render(",");
       pp(_stmdecls.listid_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.StmInit)
    {
       calc.Absyn.StmInit _stminit = (calc.Absyn.StmInit) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_stminit.type_, 0);
       pp(_stminit.id_, 0);
       render("=");
       pp(_stminit.exp_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.ReturnStm)
    {
       calc.Absyn.ReturnStm _returnstm = (calc.Absyn.ReturnStm) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("return");
       pp(_returnstm.stm_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.WhileStm)
    {
       calc.Absyn.WhileStm _whilestm = (calc.Absyn.WhileStm) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("while");
       render("(");
       pp(_whilestm.exp_, 0);
       render(")");
       pp(_whilestm.stm_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.IfStm)
    {
       calc.Absyn.IfStm _ifstm = (calc.Absyn.IfStm) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("if");
       render("(");
       pp(_ifstm.exp_, 0);
       render(")");
       pp(_ifstm.stm_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.BlockStm)
    {
       calc.Absyn.BlockStm _blockstm = (calc.Absyn.BlockStm) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("{");
       pp(_blockstm.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.TypeDefStm)
    {
       calc.Absyn.TypeDefStm _typedefstm = (calc.Absyn.TypeDefStm) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("typedef");
       pp(_typedefstm.type_, 0);
       pp(_typedefstm.id_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.ConstTypeDefStm)
    {
       calc.Absyn.ConstTypeDefStm _consttypedefstm = (calc.Absyn.ConstTypeDefStm) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("typedef");
       render("const");
       pp(_consttypedefstm.type_, 0);
       pp(_consttypedefstm.id_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(calc.Absyn.ListStm foo, int _i_)
  {
    ppListStm(foo.iterator(), _i_);
  }

  private static void ppListStm(java.util.Iterator<calc.Absyn.Stm> it, int _i_)
  {
    if (it.hasNext())
    { /* cons */
      calc.Absyn.Stm el = it.next();
      pp(el, _i_); ppListStm(it, _i_);
    }
  }


  private static void pp(calc.Absyn.Exp foo, int _i_)
  {
    if (foo instanceof calc.Absyn.LShift)
    {
       calc.Absyn.LShift _lshift = (calc.Absyn.LShift) foo;
       if (_i_ > 10) render(_L_PAREN);
       pp(_lshift.exp_1, 10);
       render("<<");
       pp(_lshift.exp_2, 11);
       if (_i_ > 10) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.RShift)
    {
       calc.Absyn.RShift _rshift = (calc.Absyn.RShift) foo;
       if (_i_ > 10) render(_L_PAREN);
       pp(_rshift.exp_1, 10);
       render(">>");
       pp(_rshift.exp_2, 11);
       if (_i_ > 10) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.IndexExp)
    {
       calc.Absyn.IndexExp _indexexp = (calc.Absyn.IndexExp) foo;
       if (_i_ > 14) render(_L_PAREN);
       pp(_indexexp.exp_1, 14);
       render("[");
       pp(_indexexp.exp_2, 0);
       render("]");
       if (_i_ > 14) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.FunCallExp)
    {
       calc.Absyn.FunCallExp _funcallexp = (calc.Absyn.FunCallExp) foo;
       if (_i_ > 14) render(_L_PAREN);
       pp(_funcallexp.exp_, 14);
       render("(");
       pp(_funcallexp.listexp_, 0);
       render(")");
       if (_i_ > 14) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.IntExp)
    {
       calc.Absyn.IntExp _intexp = (calc.Absyn.IntExp) foo;
       if (_i_ > 15) render(_L_PAREN);
       pp(_intexp.integer_, 0);
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.DoubleExp)
    {
       calc.Absyn.DoubleExp _doubleexp = (calc.Absyn.DoubleExp) foo;
       if (_i_ > 15) render(_L_PAREN);
       pp(_doubleexp.double_, 0);
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.StringExp)
    {
       calc.Absyn.StringExp _stringexp = (calc.Absyn.StringExp) foo;
       if (_i_ > 15) render(_L_PAREN);
       printQuoted(_stringexp.string_);
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.QualConstExp)
    {
       calc.Absyn.QualConstExp _qualconstexp = (calc.Absyn.QualConstExp) foo;
       if (_i_ > 15) render(_L_PAREN);
       pp(_qualconstexp.listid_, 0);
       if (_i_ > 15) render(_R_PAREN);
    }

  }

  private static void pp(calc.Absyn.ListExp foo, int _i_)
  {
    ppListExp(foo.iterator(), _i_);
  }

  private static void ppListExp(java.util.Iterator<calc.Absyn.Exp> it, int _i_)
  {
    if (it.hasNext())
    {
      calc.Absyn.Exp el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListExp(it, _i_);
      }
    }
  }


  private static void pp(calc.Absyn.ListId foo, int _i_)
  {
    ppListId(foo.iterator(), _i_);
  }

  private static void ppListId(java.util.Iterator<String> it, int _i_)
  {
    if (it.hasNext())
    {
      String el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render("::"); ppListId(it, _i_);
      }
    }
  }


  private static void pp(calc.Absyn.Type foo, int _i_)
  {
    if (foo instanceof calc.Absyn.BoolType)
    {
       calc.Absyn.BoolType _booltype = (calc.Absyn.BoolType) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bool");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.DoubleType)
    {
       calc.Absyn.DoubleType _doubletype = (calc.Absyn.DoubleType) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("double");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.IntType)
    {
       calc.Absyn.IntType _inttype = (calc.Absyn.IntType) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("int");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof calc.Absyn.VoidType)
    {
       calc.Absyn.VoidType _voidtype = (calc.Absyn.VoidType) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("void");
       if (_i_ > 0) render(_R_PAREN);
    }

  }


  private static void sh(calc.Absyn.Program foo)
  {
    if (foo instanceof calc.Absyn.ProgDef)
    {
       calc.Absyn.ProgDef _progdef = (calc.Absyn.ProgDef) foo;
       render("(");
       render("ProgDef");
       render("[");
       sh(_progdef.listdef_);
       render("]");
       render(")");
    }
  }

  private static void sh(calc.Absyn.Def foo)
  {
    if (foo instanceof calc.Absyn.QualConstDef)
    {
       calc.Absyn.QualConstDef _qualconstdef = (calc.Absyn.QualConstDef) foo;
       render("(");
       render("QualConstDef");
       sh(_qualconstdef.exp_);
       render(")");
    }
    if (foo instanceof calc.Absyn.FuncDef)
    {
       calc.Absyn.FuncDef _funcdef = (calc.Absyn.FuncDef) foo;
       render("(");
       render("FuncDef");
       sh(_funcdef.type_);
       sh(_funcdef.id_);
       render("[");
       sh(_funcdef.listarg_);
       render("]");
       render("[");
       sh(_funcdef.liststm_);
       render("]");
       render(")");
    }
  }

  private static void sh(calc.Absyn.ListDef foo)
  {
     for (java.util.Iterator<calc.Absyn.Def> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(calc.Absyn.ListArg foo)
  {
     for (java.util.Iterator<calc.Absyn.Arg> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(calc.Absyn.Arg foo)
  {
    if (foo instanceof calc.Absyn.ArgDecl)
    {
       calc.Absyn.ArgDecl _argdecl = (calc.Absyn.ArgDecl) foo;
       render("(");
       render("ArgDecl");
       sh(_argdecl.type_);
       sh(_argdecl.id_);
       render(")");
    }
  }

  private static void sh(calc.Absyn.Stm foo)
  {
    if (foo instanceof calc.Absyn.StmDef)
    {
       calc.Absyn.StmDef _stmdef = (calc.Absyn.StmDef) foo;
       render("(");
       render("StmDef");
       sh(_stmdef.exp_);
       render(")");
    }
    if (foo instanceof calc.Absyn.StmDecl)
    {
       calc.Absyn.StmDecl _stmdecl = (calc.Absyn.StmDecl) foo;
       render("(");
       render("StmDecl");
       sh(_stmdecl.type_);
       sh(_stmdecl.id_);
       render(")");
    }
    if (foo instanceof calc.Absyn.StmDecl2)
    {
       calc.Absyn.StmDecl2 _stmdecl2 = (calc.Absyn.StmDecl2) foo;
       render("(");
       render("StmDecl2");
       sh(_stmdecl2.exp_);
       sh(_stmdecl2.id_);
       render(")");
    }
    if (foo instanceof calc.Absyn.StmDecls)
    {
       calc.Absyn.StmDecls _stmdecls = (calc.Absyn.StmDecls) foo;
       render("(");
       render("StmDecls");
       sh(_stmdecls.type_);
       sh(_stmdecls.id_);
       render("[");
       sh(_stmdecls.listid_);
       render("]");
       render(")");
    }
    if (foo instanceof calc.Absyn.StmInit)
    {
       calc.Absyn.StmInit _stminit = (calc.Absyn.StmInit) foo;
       render("(");
       render("StmInit");
       sh(_stminit.type_);
       sh(_stminit.id_);
       sh(_stminit.exp_);
       render(")");
    }
    if (foo instanceof calc.Absyn.ReturnStm)
    {
       calc.Absyn.ReturnStm _returnstm = (calc.Absyn.ReturnStm) foo;
       render("(");
       render("ReturnStm");
       sh(_returnstm.stm_);
       render(")");
    }
    if (foo instanceof calc.Absyn.WhileStm)
    {
       calc.Absyn.WhileStm _whilestm = (calc.Absyn.WhileStm) foo;
       render("(");
       render("WhileStm");
       sh(_whilestm.exp_);
       sh(_whilestm.stm_);
       render(")");
    }
    if (foo instanceof calc.Absyn.IfStm)
    {
       calc.Absyn.IfStm _ifstm = (calc.Absyn.IfStm) foo;
       render("(");
       render("IfStm");
       sh(_ifstm.exp_);
       sh(_ifstm.stm_);
       render(")");
    }
    if (foo instanceof calc.Absyn.BlockStm)
    {
       calc.Absyn.BlockStm _blockstm = (calc.Absyn.BlockStm) foo;
       render("(");
       render("BlockStm");
       render("[");
       sh(_blockstm.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof calc.Absyn.TypeDefStm)
    {
       calc.Absyn.TypeDefStm _typedefstm = (calc.Absyn.TypeDefStm) foo;
       render("(");
       render("TypeDefStm");
       sh(_typedefstm.type_);
       sh(_typedefstm.id_);
       render(")");
    }
    if (foo instanceof calc.Absyn.ConstTypeDefStm)
    {
       calc.Absyn.ConstTypeDefStm _consttypedefstm = (calc.Absyn.ConstTypeDefStm) foo;
       render("(");
       render("ConstTypeDefStm");
       sh(_consttypedefstm.type_);
       sh(_consttypedefstm.id_);
       render(")");
    }
  }

  private static void sh(calc.Absyn.ListStm foo)
  {
     for (java.util.Iterator<calc.Absyn.Stm> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(calc.Absyn.Exp foo)
  {
    if (foo instanceof calc.Absyn.LShift)
    {
       calc.Absyn.LShift _lshift = (calc.Absyn.LShift) foo;
       render("(");
       render("LShift");
       sh(_lshift.exp_1);
       sh(_lshift.exp_2);
       render(")");
    }
    if (foo instanceof calc.Absyn.RShift)
    {
       calc.Absyn.RShift _rshift = (calc.Absyn.RShift) foo;
       render("(");
       render("RShift");
       sh(_rshift.exp_1);
       sh(_rshift.exp_2);
       render(")");
    }
    if (foo instanceof calc.Absyn.IndexExp)
    {
       calc.Absyn.IndexExp _indexexp = (calc.Absyn.IndexExp) foo;
       render("(");
       render("IndexExp");
       sh(_indexexp.exp_1);
       sh(_indexexp.exp_2);
       render(")");
    }
    if (foo instanceof calc.Absyn.FunCallExp)
    {
       calc.Absyn.FunCallExp _funcallexp = (calc.Absyn.FunCallExp) foo;
       render("(");
       render("FunCallExp");
       sh(_funcallexp.exp_);
       render("[");
       sh(_funcallexp.listexp_);
       render("]");
       render(")");
    }
    if (foo instanceof calc.Absyn.IntExp)
    {
       calc.Absyn.IntExp _intexp = (calc.Absyn.IntExp) foo;
       render("(");
       render("IntExp");
       sh(_intexp.integer_);
       render(")");
    }
    if (foo instanceof calc.Absyn.DoubleExp)
    {
       calc.Absyn.DoubleExp _doubleexp = (calc.Absyn.DoubleExp) foo;
       render("(");
       render("DoubleExp");
       sh(_doubleexp.double_);
       render(")");
    }
    if (foo instanceof calc.Absyn.StringExp)
    {
       calc.Absyn.StringExp _stringexp = (calc.Absyn.StringExp) foo;
       render("(");
       render("StringExp");
       sh(_stringexp.string_);
       render(")");
    }
    if (foo instanceof calc.Absyn.QualConstExp)
    {
       calc.Absyn.QualConstExp _qualconstexp = (calc.Absyn.QualConstExp) foo;
       render("(");
       render("QualConstExp");
       render("[");
       sh(_qualconstexp.listid_);
       render("]");
       render(")");
    }
  }

  private static void sh(calc.Absyn.ListExp foo)
  {
     for (java.util.Iterator<calc.Absyn.Exp> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(calc.Absyn.ListId foo)
  {
     for (java.util.Iterator<String> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(calc.Absyn.Type foo)
  {
    if (foo instanceof calc.Absyn.BoolType)
    {
       calc.Absyn.BoolType _booltype = (calc.Absyn.BoolType) foo;
       render("BoolType");
    }
    if (foo instanceof calc.Absyn.DoubleType)
    {
       calc.Absyn.DoubleType _doubletype = (calc.Absyn.DoubleType) foo;
       render("DoubleType");
    }
    if (foo instanceof calc.Absyn.IntType)
    {
       calc.Absyn.IntType _inttype = (calc.Absyn.IntType) foo;
       render("IntType");
    }
    if (foo instanceof calc.Absyn.VoidType)
    {
       calc.Absyn.VoidType _voidtype = (calc.Absyn.VoidType) foo;
       render("VoidType");
    }
  }


  private static void pp(Integer n, int _i_) { buf_.append(n); buf_.append(" "); }
  private static void pp(Double d, int _i_) { buf_.append(String.format(java.util.Locale.ROOT, "%.15g ", d)); }
  private static void pp(String s, int _i_) { buf_.append(s); buf_.append(" "); }
  private static void pp(Character c, int _i_) { buf_.append("'" + c.toString() + "'"); buf_.append(" "); }
  private static void sh(Integer n) { render(n.toString()); }
  private static void sh(Double d) { render(String.format(java.util.Locale.ROOT, "%.15g", d)); }
  private static void sh(Character c) { render("'" + c.toString() + "'"); }
  private static void sh(String s) { printQuoted(s); }

  private static void printQuoted(String s) { render("\"" + s + "\""); }

  private static void indent()
  {
    int n = _n_;
    while (n > 0)
    {
      buf_.append(' ');
      n--;
    }
  }

  private static void backup()
  {
    int prev = buf_.length() - 1;
    if (prev >= 0 && buf_.charAt(prev) == ' ')
      buf_.setLength(prev);
  }

  private static void trim()
  {
    // Trim initial spaces
    int end = 0;
    int len = buf_.length();
    while (end < len && buf_.charAt(end) == ' ')
      end++;
    buf_.delete(0, end);
    // Trim trailing spaces
    removeTrailingSpaces();
  }

  private static void removeTrailingSpaces()
  {
    int end = buf_.length();
    while (end > 0 && buf_.charAt(end-1) == ' ')
      end--;
    buf_.setLength(end);
  }

  private static void removeTrailingWhitespace()
  {
    int end = buf_.length();
    while (end > 0 && (buf_.charAt(end-1) == ' ' || buf_.charAt(end-1) == '\n'))
      end--;
    buf_.setLength(end);
  }

  private static void onEmptyLine()
  {
    removeTrailingSpaces();
    int len = buf_.length();
    if (len > 0 && buf_.charAt(len-1) != '\n') buf_.append("\n");
    indent();
  }

  private static int _n_ = 0;
  private static StringBuilder buf_ = new StringBuilder(INITIAL_BUFFER_SIZE);
}

