// File generated by the BNF Converter (bnfc 2.9.3).

package calc;

/*** Visitor Design Pattern Skeleton. ***/

/* This implements the common visitor design pattern.
   Tests show it to be slightly less efficient than the
   instanceof method, but easier to use.
   Replace the R and A parameters with the desired return
   and context types.*/

public class VisitSkel
{
  public class ProgramVisitor<R,A> implements calc.Absyn.Program.Visitor<R,A>
  {
    public R visit(calc.Absyn.ProgDef p, A arg)
    { /* Code for ProgDef goes here */
      for (calc.Absyn.Def x: p.listdef_) {
        x.accept(new DefVisitor<R,A>(), arg);
      }
      return null;
    }
  }
  public class DefVisitor<R,A> implements calc.Absyn.Def.Visitor<R,A>
  {
    public R visit(calc.Absyn.QualConstDef p, A arg)
    { /* Code for QualConstDef goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(calc.Absyn.FuncDef p, A arg)
    { /* Code for FuncDef goes here */
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      //p.id_;
      for (calc.Absyn.Arg x: p.listarg_) {
        x.accept(new ArgVisitor<R,A>(), arg);
      }
      for (calc.Absyn.Stm x: p.liststm_) {
        x.accept(new StmVisitor<R,A>(), arg);
      }
      return null;
    }
  }
  public class ArgVisitor<R,A> implements calc.Absyn.Arg.Visitor<R,A>
  {
    public R visit(calc.Absyn.ArgDecl p, A arg)
    { /* Code for ArgDecl goes here */
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      //p.id_;
      return null;
    }
  }
  public class StmVisitor<R,A> implements calc.Absyn.Stm.Visitor<R,A>
  {
    public R visit(calc.Absyn.StmDef p, A arg)
    { /* Code for StmDef goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(calc.Absyn.StmDecl p, A arg)
    { /* Code for StmDecl goes here */
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      //p.id_;
      return null;
    }
    public R visit(calc.Absyn.StmDecl2 p, A arg)
    { /* Code for StmDecl2 goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      //p.id_;
      return null;
    }
    public R visit(calc.Absyn.StmDecls p, A arg)
    { /* Code for StmDecls goes here */
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      //p.id_;
      for (String x: p.listid_) {
        //x;
      }
      return null;
    }
    public R visit(calc.Absyn.StmInit p, A arg)
    { /* Code for StmInit goes here */
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      //p.id_;
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(calc.Absyn.ReturnStm p, A arg)
    { /* Code for ReturnStm goes here */
      p.stm_.accept(new StmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(calc.Absyn.WhileStm p, A arg)
    { /* Code for WhileStm goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      p.stm_.accept(new StmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(calc.Absyn.IfStm p, A arg)
    { /* Code for IfStm goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      p.stm_.accept(new StmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(calc.Absyn.BlockStm p, A arg)
    { /* Code for BlockStm goes here */
      for (calc.Absyn.Stm x: p.liststm_) {
        x.accept(new StmVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(calc.Absyn.TypeDefStm p, A arg)
    { /* Code for TypeDefStm goes here */
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      //p.id_;
      return null;
    }
    public R visit(calc.Absyn.ConstTypeDefStm p, A arg)
    { /* Code for ConstTypeDefStm goes here */
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      //p.id_;
      return null;
    }
  }
  public class ExpVisitor<R,A> implements calc.Absyn.Exp.Visitor<R,A>
  {
    public R visit(calc.Absyn.LShift p, A arg)
    { /* Code for LShift goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(calc.Absyn.RShift p, A arg)
    { /* Code for RShift goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(calc.Absyn.IndexExp p, A arg)
    { /* Code for IndexExp goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(calc.Absyn.FunCallExp p, A arg)
    { /* Code for FunCallExp goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      for (calc.Absyn.Exp x: p.listexp_) {
        x.accept(new ExpVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(calc.Absyn.IntExp p, A arg)
    { /* Code for IntExp goes here */
      //p.integer_;
      return null;
    }
    public R visit(calc.Absyn.DoubleExp p, A arg)
    { /* Code for DoubleExp goes here */
      //p.double_;
      return null;
    }
    public R visit(calc.Absyn.StringExp p, A arg)
    { /* Code for StringExp goes here */
      //p.string_;
      return null;
    }
    public R visit(calc.Absyn.QualConstExp p, A arg)
    { /* Code for QualConstExp goes here */
      for (String x: p.listid_) {
        //x;
      }
      return null;
    }
  }
  public class TypeVisitor<R,A> implements calc.Absyn.Type.Visitor<R,A>
  {
    public R visit(calc.Absyn.BoolType p, A arg)
    { /* Code for BoolType goes here */
      return null;
    }
    public R visit(calc.Absyn.DoubleType p, A arg)
    { /* Code for DoubleType goes here */
      return null;
    }
    public R visit(calc.Absyn.IntType p, A arg)
    { /* Code for IntType goes here */
      return null;
    }
    public R visit(calc.Absyn.VoidType p, A arg)
    { /* Code for VoidType goes here */
      return null;
    }
  }
}
