// -*- Java -*- File generated by the BNF Converter (bnfc 2.9.3).
// Lexer definition for use with JLex
package calc;
import java_cup.runtime.*;


public class Yylex implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 65536;
	private final int YY_EOF = 65537;

  String pstring = new String();
  final int unknown = -1;
  ComplexSymbolFactory.Location left = new ComplexSymbolFactory.Location(unknown, unknown);
  ComplexSymbolFactory cf = new ComplexSymbolFactory();
  public SymbolFactory getSymbolFactory() { return cf; }
  int yyline = unknown - 1;
  int yycolumn = unknown - 1;
  int yychar = unknown;
  public int line_num() { return (yyline+1); }
  public ComplexSymbolFactory.Location left_loc() {
    return left;
  }
  public ComplexSymbolFactory.Location right_loc() {
    ComplexSymbolFactory.Location left = left_loc();
  return left;
  }
  public String buff() {return new String(yy_buffer,yy_buffer_index,10).trim();}
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int STRING = 5;
	private final int ESCAPED = 6;
	private final int YYINITIAL = 0;
	private final int COMMENT = 1;
	private final int CHAREND = 4;
	private final int CHARESC = 3;
	private final int CHAR = 2;
	private final int yy_state_dtrans[] = {
		0,
		61,
		64,
		64,
		64,
		66,
		68
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NO_ANCHOR,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NO_ANCHOR,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NO_ANCHOR,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NO_ANCHOR,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NO_ANCHOR,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NOT_ACCEPT,
		/* 49 */ YY_NO_ANCHOR,
		/* 50 */ YY_NO_ANCHOR,
		/* 51 */ YY_NO_ANCHOR,
		/* 52 */ YY_NO_ANCHOR,
		/* 53 */ YY_NO_ANCHOR,
		/* 54 */ YY_NO_ANCHOR,
		/* 55 */ YY_NOT_ACCEPT,
		/* 56 */ YY_NO_ANCHOR,
		/* 57 */ YY_NO_ANCHOR,
		/* 58 */ YY_NOT_ACCEPT,
		/* 59 */ YY_NO_ANCHOR,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NOT_ACCEPT,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NO_ANCHOR,
		/* 64 */ YY_NOT_ACCEPT,
		/* 65 */ YY_NO_ANCHOR,
		/* 66 */ YY_NOT_ACCEPT,
		/* 67 */ YY_NO_ANCHOR,
		/* 68 */ YY_NOT_ACCEPT,
		/* 69 */ YY_NO_ANCHOR,
		/* 70 */ YY_NO_ANCHOR,
		/* 71 */ YY_NO_ANCHOR,
		/* 72 */ YY_NO_ANCHOR,
		/* 73 */ YY_NO_ANCHOR,
		/* 74 */ YY_NO_ANCHOR,
		/* 75 */ YY_NO_ANCHOR,
		/* 76 */ YY_NO_ANCHOR,
		/* 77 */ YY_NO_ANCHOR,
		/* 78 */ YY_NO_ANCHOR,
		/* 79 */ YY_NO_ANCHOR,
		/* 80 */ YY_NO_ANCHOR,
		/* 81 */ YY_NO_ANCHOR,
		/* 82 */ YY_NO_ANCHOR,
		/* 83 */ YY_NO_ANCHOR,
		/* 84 */ YY_NO_ANCHOR,
		/* 85 */ YY_NO_ANCHOR,
		/* 86 */ YY_NO_ANCHOR,
		/* 87 */ YY_NO_ANCHOR,
		/* 88 */ YY_NO_ANCHOR,
		/* 89 */ YY_NO_ANCHOR,
		/* 90 */ YY_NO_ANCHOR,
		/* 91 */ YY_NO_ANCHOR,
		/* 92 */ YY_NO_ANCHOR,
		/* 93 */ YY_NO_ANCHOR,
		/* 94 */ YY_NO_ANCHOR,
		/* 95 */ YY_NO_ANCHOR,
		/* 96 */ YY_NO_ANCHOR,
		/* 97 */ YY_NO_ANCHOR,
		/* 98 */ YY_NO_ANCHOR,
		/* 99 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"36:9,46,37,36,46,33,36:18,46,36,42,34,36:4,2,3,35,36,6,45,44,32,41:10,12,1," +
"8,7,9,36:2,38:26,10,43,11,36,40,36,39,13,16,20,22,24,28,31,23,39:2,15,39,17" +
",14,27,39,25,18,19,21,29,30,39,26,39,4,36,5,36:66,38:23,36,38:7,39:24,36,39" +
":8,36:65280,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,100,
"0,1:8,2,1:2,3,1,4,5,1:4,6,7,1,6,8,6:8,1:4,9,1:7,10,1:2,11,12,13,14,15,1:2,1" +
"6,17,18,14,19,20,21,1,22,23,24,25,26,27,28,29,30,31,32,6,33,34,35,36,37,38," +
"39,40,41,42,43,44,45,46,47,48,6,49,50,51,52,53,54,55,56")[0];

	private int yy_nxt[][] = unpackFromString(57,47,
"1,2,3,4,5,6,7,8,9,49,10,11,56,12,91:2,93,91:2,94,95,96,91,50,91,97,91:3,98," +
"99,91,59,13,14,62:2,13,91:2,62,15,16,62:3,13,-1:55,17,-1:51,91,73,91:17,-1:" +
"6,74,91,74:2,-1:6,14:36,-1,14:9,-1:41,15,-1:2,48,-1:15,91:19,-1:6,74,91,74:" +
"2,-1:6,21:36,-1,21:9,-1:22,55,-1:18,24,-1:42,53,-1:46,54,-1:50,24,-1:14,18," +
"-1:50,91:4,57,91:6,20,91:7,-1:6,74,91,74:2,-1:46,51,-1:37,35,-1:55,51,-1:3," +
"58,-1:13,19,-1:47,91:6,23,91:12,-1:6,74,91,74:2,-1:37,21,-1:2,22,-1:24,91:2" +
",25,91:16,-1:6,74,91,74:2,-1:5,1,33:32,-1,33,52,33,34,33:9,-1:13,91:7,26,91" +
":11,-1:6,74,91,74:2,-1:5,1,62:32,-1,62:3,-1,62:9,-1:13,91:6,27,91:12,-1:6,7" +
"4,91,74:2,-1:5,1,36:32,37,36:3,53,36:4,38,39,36:3,-1:13,91:15,28,91:3,-1:6," +
"74,91,74:2,-1:5,1,40:16,41,40,42,40:4,43,44,40:7,45,40:3,54,40:4,46,47,40:3" +
",-1:13,91:9,29,91:9,-1:6,74,91,74:2,-1:18,91:9,30,91:9,-1:6,74,91,74:2,-1:1" +
"8,91:4,31,91:14,-1:6,74,91,74:2,-1:18,91:11,32,91:7,-1:6,74,91,74:2,-1:18,9" +
"1,60,91:17,-1:6,74,91,74:2,-1:18,91:4,81,91:14,-1:6,74,91,74:2,-1:18,91:14," +
"82,91:4,-1:6,74,91,74:2,-1:18,91:8,83,91:10,-1:6,74,91,74:2,-1:18,91:10,84," +
"91:8,-1:6,74,91,74:2,-1:18,91:6,85,91:12,-1:6,74,91,74:2,-1:18,91:10,63,91:" +
"8,-1:6,74,91,74:2,-1:18,91:5,65,91:13,-1:6,74,91,74:2,-1:18,91:9,87,91:9,-1" +
":6,74,91,74:2,-1:18,88,91:18,-1:6,74,91,74:2,-1:18,91:4,67,91:14,-1:6,74,91" +
",74:2,-1:18,91:8,89,91:10,-1:6,74,91,74:2,-1:18,91:2,69,91:16,-1:6,74,91,74" +
":2,-1:18,91:7,90,91:11,-1:6,74,91,74:2,-1:18,91:2,70,91:16,-1:6,74,91,74:2," +
"-1:18,91:12,71,91:6,-1:6,74,91,74:2,-1:18,91:9,72,91:9,-1:6,74,91,74:2,-1:1" +
"8,91:10,86,91:8,-1:6,74,91,74:2,-1:18,91,75,91:17,-1:6,74,91,74:2,-1:18,91:" +
"13,76,91:5,-1:6,74,91,74:2,-1:18,91,77,91:17,-1:6,74,91,74:2,-1:18,91:5,78," +
"91:13,-1:6,74,91,74:2,-1:18,91:9,79,91:9,-1:6,74,91,74:2,-1:18,91,80,91:17," +
"-1:6,74,91,74:2,-1:18,91:18,92,-1:6,74,91,74:2,-1:5");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {

  return cf.newSymbol("EOF", sym.EOF, left_loc(), left_loc());
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return cf.newSymbol("", sym._SYMB_0, left_loc(), right_loc()); }
					case -3:
						break;
					case 3:
						{ return cf.newSymbol("", sym._SYMB_1, left_loc(), right_loc()); }
					case -4:
						break;
					case 4:
						{ return cf.newSymbol("", sym._SYMB_2, left_loc(), right_loc()); }
					case -5:
						break;
					case 5:
						{ return cf.newSymbol("", sym._SYMB_3, left_loc(), right_loc()); }
					case -6:
						break;
					case 6:
						{ return cf.newSymbol("", sym._SYMB_4, left_loc(), right_loc()); }
					case -7:
						break;
					case 7:
						{ return cf.newSymbol("", sym._SYMB_5, left_loc(), right_loc()); }
					case -8:
						break;
					case 8:
						{ return cf.newSymbol("", sym._SYMB_6, left_loc(), right_loc()); }
					case -9:
						break;
					case 9:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -10:
						break;
					case 10:
						{ return cf.newSymbol("", sym._SYMB_9, left_loc(), right_loc()); }
					case -11:
						break;
					case 11:
						{ return cf.newSymbol("", sym._SYMB_10, left_loc(), right_loc()); }
					case -12:
						break;
					case 12:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -13:
						break;
					case 13:
						{ /* ignore white space. */ }
					case -14:
						break;
					case 14:
						{ /* skip */ }
					case -15:
						break;
					case 15:
						{ return cf.newSymbol("", sym._INTEGER_, left_loc(), right_loc(), new Integer(yytext())); }
					case -16:
						break;
					case 16:
						{ left = left_loc(); yybegin(STRING); }
					case -17:
						break;
					case 17:
						{ return cf.newSymbol("", sym._SYMB_7, left_loc(), right_loc()); }
					case -18:
						break;
					case 18:
						{ return cf.newSymbol("", sym._SYMB_8, left_loc(), right_loc()); }
					case -19:
						break;
					case 19:
						{ return cf.newSymbol("", sym._SYMB_11, left_loc(), right_loc()); }
					case -20:
						break;
					case 20:
						{ return cf.newSymbol("", sym._SYMB_15, left_loc(), right_loc()); }
					case -21:
						break;
					case 21:
						{ /* skip */ }
					case -22:
						break;
					case 22:
						{ yybegin(COMMENT); }
					case -23:
						break;
					case 23:
						{ return cf.newSymbol("", sym._SYMB_16, left_loc(), right_loc()); }
					case -24:
						break;
					case 24:
						{ return cf.newSymbol("", sym._DOUBLE_, left_loc(), right_loc(), new Double(yytext())); }
					case -25:
						break;
					case 25:
						{ return cf.newSymbol("", sym._SYMB_12, left_loc(), right_loc()); }
					case -26:
						break;
					case 26:
						{ return cf.newSymbol("", sym._SYMB_20, left_loc(), right_loc()); }
					case -27:
						break;
					case 27:
						{ return cf.newSymbol("", sym._SYMB_13, left_loc(), right_loc()); }
					case -28:
						break;
					case 28:
						{ return cf.newSymbol("", sym._SYMB_19, left_loc(), right_loc()); }
					case -29:
						break;
					case 29:
						{ return cf.newSymbol("", sym._SYMB_21, left_loc(), right_loc()); }
					case -30:
						break;
					case 30:
						{ return cf.newSymbol("", sym._SYMB_14, left_loc(), right_loc()); }
					case -31:
						break;
					case 31:
						{ return cf.newSymbol("", sym._SYMB_17, left_loc(), right_loc()); }
					case -32:
						break;
					case 32:
						{ return cf.newSymbol("", sym._SYMB_18, left_loc(), right_loc()); }
					case -33:
						break;
					case 33:
						{ /* skip */ }
					case -34:
						break;
					case 34:
						{ /* skip */ }
					case -35:
						break;
					case 35:
						{ yybegin(YYINITIAL); }
					case -36:
						break;
					case 36:
						{ pstring += yytext(); }
					case -37:
						break;
					case 37:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -38:
						break;
					case 38:
						{ String foo = pstring; pstring = new String(); yybegin(YYINITIAL); return cf.newSymbol("", sym._STRING_, left, right_loc(), foo.intern()); }
					case -39:
						break;
					case 39:
						{ yybegin(ESCAPED); }
					case -40:
						break;
					case 40:
						{ pstring += yytext(); yybegin(STRING); }
					case -41:
						break;
					case 41:
						{ pstring +=  "\n"; yybegin(STRING); }
					case -42:
						break;
					case 42:
						{ pstring += "\t"; yybegin(STRING); }
					case -43:
						break;
					case 43:
						{ pstring += "\f"; yybegin(STRING); }
					case -44:
						break;
					case 44:
						{ pstring += "\r"; yybegin(STRING); }
					case -45:
						break;
					case 45:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -46:
						break;
					case 46:
						{ pstring += "\""; yybegin(STRING); }
					case -47:
						break;
					case 47:
						{ pstring += "\\"; yybegin(STRING); }
					case -48:
						break;
					case 49:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -49:
						break;
					case 50:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -50:
						break;
					case 51:
						{ return cf.newSymbol("", sym._DOUBLE_, left_loc(), right_loc(), new Double(yytext())); }
					case -51:
						break;
					case 52:
						{ /* skip */ }
					case -52:
						break;
					case 53:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -53:
						break;
					case 54:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -54:
						break;
					case 56:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -55:
						break;
					case 57:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -56:
						break;
					case 59:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -57:
						break;
					case 60:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -58:
						break;
					case 62:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -59:
						break;
					case 63:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -60:
						break;
					case 65:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -61:
						break;
					case 67:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -62:
						break;
					case 69:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -63:
						break;
					case 70:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -64:
						break;
					case 71:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -65:
						break;
					case 72:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -66:
						break;
					case 73:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -67:
						break;
					case 74:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -68:
						break;
					case 75:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -69:
						break;
					case 76:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -70:
						break;
					case 77:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -71:
						break;
					case 78:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -72:
						break;
					case 79:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -73:
						break;
					case 80:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -74:
						break;
					case 81:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -75:
						break;
					case 82:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -76:
						break;
					case 83:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -77:
						break;
					case 84:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -78:
						break;
					case 85:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -79:
						break;
					case 86:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -80:
						break;
					case 87:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -81:
						break;
					case 88:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -82:
						break;
					case 89:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -83:
						break;
					case 90:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -84:
						break;
					case 91:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -85:
						break;
					case 92:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -86:
						break;
					case 93:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -87:
						break;
					case 94:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -88:
						break;
					case 95:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -89:
						break;
					case 96:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -90:
						break;
					case 97:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -91:
						break;
					case 98:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -92:
						break;
					case 99:
						{ return cf.newSymbol("", sym.Id, left_loc(), right_loc(), yytext().intern()); }
					case -93:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
