// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class BlockStm  extends Stm {
  public final ListStm liststm_;
  public BlockStm(ListStm p1) { liststm_ = p1; }

  public <R,A> R accept(calc.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.BlockStm) {
      calc.Absyn.BlockStm x = (calc.Absyn.BlockStm)o;
      return this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststm_.hashCode();
  }


}
