// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class CharExp  extends Exp {
  public final Character char_;
  public CharExp(Character p1) { char_ = p1; }

  public <R,A> R accept(calc.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.CharExp) {
      calc.Absyn.CharExp x = (calc.Absyn.CharExp)o;
      return this.char_.equals(x.char_);
    }
    return false;
  }

  public int hashCode() {
    return this.char_.hashCode();
  }


}
