// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public abstract class Def implements java.io.Serializable {
  public abstract <R,A> R accept(Def.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(calc.Absyn.QualConstDef p, A arg);
    public R visit(calc.Absyn.FuncDef p, A arg);

  }

}
