// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class EDouble  extends Exp {
  public final Double double_;
  public EDouble(Double p1) { double_ = p1; }

  public <R,A> R accept(calc.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.EDouble) {
      calc.Absyn.EDouble x = (calc.Absyn.EDouble)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
