// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(calc.Absyn.LShift p, A arg);
    public R visit(calc.Absyn.RShift p, A arg);
    public R visit(calc.Absyn.IndexExp p, A arg);
    public R visit(calc.Absyn.FunCallExp p, A arg);
    public R visit(calc.Absyn.IntExp p, A arg);
    public R visit(calc.Absyn.DoubleExp p, A arg);
    public R visit(calc.Absyn.StringExp p, A arg);
    public R visit(calc.Absyn.QualConstExp p, A arg);

  }

}
