// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class FunCallExp  extends Exp {
  public final Exp exp_;
  public final ListExp listexp_;
  public FunCallExp(Exp p1, ListExp p2) { exp_ = p1; listexp_ = p2; }

  public <R,A> R accept(calc.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.FunCallExp) {
      calc.Absyn.FunCallExp x = (calc.Absyn.FunCallExp)o;
      return this.exp_.equals(x.exp_) && this.listexp_.equals(x.listexp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.exp_.hashCode())+this.listexp_.hashCode();
  }


}
