// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class IdExpAssi  extends IEAssi {
  public final String id_;
  public final Exp exp_;
  public IdExpAssi(String p1, Exp p2) { id_ = p1; exp_ = p2; }

  public <R,A> R accept(calc.Absyn.IEAssi.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.IdExpAssi) {
      calc.Absyn.IdExpAssi x = (calc.Absyn.IdExpAssi)o;
      return this.id_.equals(x.id_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.id_.hashCode())+this.exp_.hashCode();
  }


}
