// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public abstract class Init implements java.io.Serializable {
  public abstract <R,A> R accept(Init.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(calc.Absyn.InitDecl p, A arg);
    public R visit(calc.Absyn.InitAssign p, A arg);

  }

}
