// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class InitStm  extends Stm {
  public final GenType gentype_;
  public final ListInit listinit_;
  public InitStm(GenType p1, ListInit p2) { gentype_ = p1; listinit_ = p2; }

  public <R,A> R accept(calc.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.InitStm) {
      calc.Absyn.InitStm x = (calc.Absyn.InitStm)o;
      return this.gentype_.equals(x.gentype_) && this.listinit_.equals(x.listinit_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.gentype_.hashCode())+this.listinit_.hashCode();
  }


}
