// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class IntExp  extends Exp {
  public final Integer integer_;
  public IntExp(Integer p1) { integer_ = p1; }

  public <R,A> R accept(calc.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.IntExp) {
      calc.Absyn.IntExp x = (calc.Absyn.IntExp)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
