// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class LQualConstShift  extends Exp {
  public final QualConst qualconst_;
  public final Exp exp_;
  public LQualConstShift(QualConst p1, Exp p2) { qualconst_ = p1; exp_ = p2; }

  public <R,A> R accept(calc.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.LQualConstShift) {
      calc.Absyn.LQualConstShift x = (calc.Absyn.LQualConstShift)o;
      return this.qualconst_.equals(x.qualconst_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.qualconst_.hashCode())+this.exp_.hashCode();
  }


}
