// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class ProgDef  extends Program {
  public final ListDef listdef_;
  public ProgDef(ListDef p1) { listdef_ = p1; }

  public <R,A> R accept(calc.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.ProgDef) {
      calc.Absyn.ProgDef x = (calc.Absyn.ProgDef)o;
      return this.listdef_.equals(x.listdef_);
    }
    return false;
  }

  public int hashCode() {
    return this.listdef_.hashCode();
  }


}
