// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class QualConstExp  extends Exp {
  public final QualConst qualconst_;
  public QualConstExp(QualConst p1) { qualconst_ = p1; }

  public <R,A> R accept(calc.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.QualConstExp) {
      calc.Absyn.QualConstExp x = (calc.Absyn.QualConstExp)o;
      return this.qualconst_.equals(x.qualconst_);
    }
    return false;
  }

  public int hashCode() {
    return this.qualconst_.hashCode();
  }


}
