// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class QualConstDef  extends Def {
  public final QualConst qualconst_;
  public QualConstDef(QualConst p1) { qualconst_ = p1; }

  public <R,A> R accept(calc.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.QualConstDef) {
      calc.Absyn.QualConstDef x = (calc.Absyn.QualConstDef)o;
      return this.qualconst_.equals(x.qualconst_);
    }
    return false;
  }

  public int hashCode() {
    return this.qualconst_.hashCode();
  }


}
