// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class ReturnStm  extends Stm {
  public final Stm stm_;
  public ReturnStm(Stm p1) { stm_ = p1; }

  public <R,A> R accept(calc.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.ReturnStm) {
      calc.Absyn.ReturnStm x = (calc.Absyn.ReturnStm)o;
      return this.stm_.equals(x.stm_);
    }
    return false;
  }

  public int hashCode() {
    return this.stm_.hashCode();
  }


}
