// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class RQualConstShift  extends Exp {
  public final Exp exp_;
  public final QualConst qualconst_;
  public RQualConstShift(Exp p1, QualConst p2) { exp_ = p1; qualconst_ = p2; }

  public <R,A> R accept(calc.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.RQualConstShift) {
      calc.Absyn.RQualConstShift x = (calc.Absyn.RQualConstShift)o;
      return this.exp_.equals(x.exp_) && this.qualconst_.equals(x.qualconst_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.exp_.hashCode())+this.qualconst_.hashCode();
  }


}
