// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class SReturn  extends Stm {
  public final Exp exp_;
  public SReturn(Exp p1) { exp_ = p1; }

  public <R,A> R accept(calc.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.SReturn) {
      calc.Absyn.SReturn x = (calc.Absyn.SReturn)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
