// File generated by the BNF Converter (bnfc 2.9.3).

package calc.Absyn;

public class StringExp  extends Exp {
  public final String string_;
  public StringExp(String p1) { string_ = p1; }

  public <R,A> R accept(calc.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof calc.Absyn.StringExp) {
      calc.Absyn.StringExp x = (calc.Absyn.StringExp)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
