// File generated by the BNF Converter (bnfc 2.9.3).

package cmm.Absyn;

public class ETyped  extends Exp {
  public final Type type_;
  public final Exp exp_;
  public ETyped(Type p1, Exp p2) { type_ = p1; exp_ = p2; }

  public <R,A> R accept(cmm.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cmm.Absyn.ETyped) {
      cmm.Absyn.ETyped x = (cmm.Absyn.ETyped)o;
      return this.type_.equals(x.type_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.exp_.hashCode();
  }


}
