// File generated by the BNF Converter (bnfc 2.9.3).

package cmm.Absyn;

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(cmm.Absyn.ETyped p, A arg);
    public R visit(cmm.Absyn.EConv p, A arg);
    public R visit(cmm.Absyn.EBool p, A arg);
    public R visit(cmm.Absyn.EInt p, A arg);
    public R visit(cmm.Absyn.EDouble p, A arg);
    public R visit(cmm.Absyn.EId p, A arg);
    public R visit(cmm.Absyn.EApp p, A arg);
    public R visit(cmm.Absyn.EPost p, A arg);
    public R visit(cmm.Absyn.EPre p, A arg);
    public R visit(cmm.Absyn.EMul p, A arg);
    public R visit(cmm.Absyn.EAdd p, A arg);
    public R visit(cmm.Absyn.ECmp p, A arg);
    public R visit(cmm.Absyn.EAnd p, A arg);
    public R visit(cmm.Absyn.EOr p, A arg);
    public R visit(cmm.Absyn.EAss p, A arg);

  }

}
